# Generated by Django 2.2.4 on 2020-04-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='competition',
            table='competition',
        ),
    ]
