# Generated by Django 2.2.4 on 2020-04-28 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(blank=True, db_column='creationDate', null=True)),
                ('kobilid', models.IntegerField(db_column='kobilId')),
                ('operationdate', models.DateTimeField(blank=True, db_column='operationDate', null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'weight',
            },
        ),
        migrations.CreateModel(
            name='GrupForReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centerreferee', models.CharField(blank=True, db_column='centerReferee', max_length=255, null=True)),
                ('compdoctor', models.CharField(blank=True, db_column='compDoctor', max_length=255, null=True)),
                ('creationdate', models.DateTimeField(blank=True, db_column='creationDate', null=True)),
                ('jurymemberfour', models.CharField(blank=True, db_column='juryMemberFour', max_length=255, null=True)),
                ('jurymemberone', models.CharField(blank=True, db_column='juryMemberOne', max_length=255, null=True)),
                ('jurymemberthree', models.CharField(blank=True, db_column='juryMemberThree', max_length=255, null=True)),
                ('jurymembertwo', models.CharField(blank=True, db_column='juryMemberTwo', max_length=255, null=True)),
                ('jurypresident', models.CharField(blank=True, db_column='juryPresident', max_length=255, null=True)),
                ('kobilid', models.IntegerField(db_column='kobilId')),
                ('marshallone', models.CharField(blank=True, db_column='marshallOne', max_length=255, null=True)),
                ('marshalltwo', models.CharField(blank=True, db_column='marshallTwo', max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('operationdate', models.DateTimeField(blank=True, db_column='operationDate', null=True)),
                ('refereeone', models.CharField(blank=True, db_column='refereeOne', max_length=255, null=True)),
                ('refereetwo', models.CharField(blank=True, db_column='refereeTwo', max_length=255, null=True)),
                ('speaker', models.CharField(blank=True, max_length=255, null=True)),
                ('techcontrollerone', models.CharField(blank=True, db_column='techControllerOne', max_length=255, null=True)),
                ('techcontrollertwo', models.CharField(blank=True, db_column='techControllerTwo', max_length=255, null=True)),
                ('timekeeper', models.CharField(blank=True, db_column='timeKeeper', max_length=255, null=True)),
                ('competition', models.ForeignKey(blank=True, db_column='competition', null=True, on_delete=django.db.models.deletion.CASCADE, to='wushu.Competition')),
            ],
            options={
                'db_table': 'grupforreport',
            },
        ),
        migrations.CreateModel(
            name='CompCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athletegroup', models.CharField(blank=True, db_column='athleteGroup', max_length=255, null=True)),
                ('creationdate', models.DateTimeField(blank=True, db_column='creationDate', null=True)),
                ('kobilid', models.IntegerField(db_column='kobilId')),
                ('operationdate', models.DateTimeField(blank=True, db_column='operationDate', null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('startdate', models.CharField(blank=True, db_column='startDate', max_length=45, null=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('starttime', models.CharField(blank=True, db_column='startTime', max_length=45, null=True)),
                ('competition', models.ForeignKey(blank=True, db_column='competition', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wushu.Competition')),
                ('grupforreport', models.ForeignKey(blank=True, db_column='grupForReport', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wushu.GrupForReport')),
            ],
            options={
                'db_table': 'compcategory',
            },
        ),
        migrations.CreateModel(
            name='CompAthlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationdate', models.DateTimeField(blank=True, db_column='creationDate', null=True)),
                ('degree', models.IntegerField()),
                ('kobilid', models.IntegerField(db_column='kobilId')),
                ('kop1', models.IntegerField()),
                ('kop1b', models.IntegerField()),
                ('kop2', models.IntegerField()),
                ('kop2b', models.IntegerField()),
                ('kop3', models.IntegerField()),
                ('kop3b', models.IntegerField()),
                ('kopdegree', models.IntegerField(db_column='kopDegree')),
                ('kopkaldirissira', models.IntegerField(db_column='kopKaldirisSira')),
                ('kopsilktotal', models.IntegerField(db_column='kopSilkTotal')),
                ('koptotal', models.IntegerField(db_column='kopTotal')),
                ('lotno', models.IntegerField(db_column='lotNo')),
                ('operationdate', models.DateTimeField(blank=True, db_column='operationDate', null=True)),
                ('sessionno', models.IntegerField(db_column='sessionNo')),
                ('silk1', models.IntegerField()),
                ('silk1b', models.IntegerField()),
                ('silk2', models.IntegerField()),
                ('silk2b', models.IntegerField()),
                ('silk3', models.IntegerField()),
                ('silk3b', models.IntegerField()),
                ('silkdegree', models.IntegerField(db_column='silkDegree')),
                ('silktotal', models.IntegerField(db_column='silkTotal')),
                ('total', models.IntegerField()),
                ('weight', models.FloatField()),
                ('lastliftvalue', models.IntegerField(blank=True, db_column='lastLiftValue', null=True)),
                ('lastsilkliftvalue', models.IntegerField(blank=True, db_column='lastSilkLiftValue', null=True)),
                ('athlete', models.ForeignKey(blank=True, db_column='athlete', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wushu.Athlete')),
                ('compcategory', models.ForeignKey(blank=True, db_column='compCategory', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wushu.CompCategory')),
                ('competition', models.ForeignKey(blank=True, db_column='competition', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wushu.Competition')),
                ('sıklet', models.ForeignKey(blank=True, db_column='sıklet', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wushu.Weight')),
            ],
            options={
                'db_table': 'compathlete',
            },
        ),
    ]
