# Generated by Django 2.2.6 on 2020-03-19 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaoluAthlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wushu.Athlete')),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wushu.Competition')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
