# Generated by Django 2.2.4 on 2020-04-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
