# Generated by Django 2.2.4 on 2020-04-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0002_auto_20200426_0208'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='competition',
            table=None,
        ),
    ]
