# Generated by Django 2.2.6 on 2020-03-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0002_taoluathlete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='startDate2',
        ),
    ]
