# Generated by Django 2.2.4 on 2020-04-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0002_auto_20200428_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
