# Generated by Django 2.2.4 on 2020-04-26 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0003_auto_20200426_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='modificationDate',
            new_name='operationDate',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='location',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='status',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='subBranch',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='type',
        ),
        migrations.AddField(
            model_name='competition',
            name='compGeneralType',
            field=models.IntegerField(blank=True, choices=[('Türkiye', 'Türkiye'), ('Dünya', 'Dünya'), ('Olimpiyat', 'Olimpiyat'), ('Avrupa', 'Avrupa')], null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='compType',
            field=models.IntegerField(blank=True, choices=[('Üniversiteler Arası', 'Üniversiteler Arası'), ('Okullar Arası', 'Okullar Arası'), ('Ferdi', 'Ferdi')], null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='eskimi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='eventDate',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='eventPlace',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='isOpen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='juryCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='registerFinishDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='registerStartDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
