# Generated by Django 2.2.6 on 2020-03-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0003_remove_competition_startdate2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SandaAthlete',
        ),
    ]
