# Generated by Django 2.2.4 on 2020-04-26 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0004_auto_20200426_1652'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='competition',
            table='competition',
        ),
    ]
