# Generated by Django 2.2.6 on 2020-03-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0005_sandaathlete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachvisa',
            name='branch',
        ),
    ]
