# Generated by Django 2.2.4 on 2020-04-30 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0006_auto_20200430_0233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'default_permissions': (), 'managed': False, 'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='categoryitem',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='communication',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='compathlete',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='compcategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sportsclub',
            options={'default_permissions': (), 'managed': False},
        ),
        migrations.RenameField(
            model_name='license',
            old_name='modificationDate',
            new_name='operationDate',
        ),
    ]
