# Generated by Django 2.2.6 on 2020-03-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0006_remove_coachvisa_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachvisa',
            name='definition',
        ),
    ]
