# Generated by Django 2.2.4 on 2020-04-30 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0007_auto_20200430_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='cityHeadShip',
            field=models.ForeignKey(db_column='cityHeadShip', on_delete=django.db.models.deletion.CASCADE, to='wushu.City'),
        ),
        migrations.AlterField(
            model_name='license',
            name='sportsClub',
            field=models.ForeignKey(db_column='sportsClub', on_delete=django.db.models.deletion.CASCADE, to='wushu.SportsClub'),
        ),
    ]
