# Generated by Django 2.2.6 on 2020-03-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0010_auto_20200324_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='branch',
            field=models.CharField(blank=True, choices=[('AIKIDO', 'AIKIDO'), ('WING CHUN', 'WING CHUN'), ('WUSHU', 'WUSHU'), ('KYOKUSHIN ASHIHARA', 'KYOKUSHIN ASHIHARA'), ('JEET KUNE DO KULELKAVIDO', 'JEET KUNE DO KULELKAVIDO')], max_length=128, null=True, verbose_name='Seçiniz'),
        ),
    ]
