# Generated by Django 2.2.6 on 2020-03-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0011_auto_20200324_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='dekont',
            field=models.FileField(upload_to='dekont/', verbose_name='Dekont '),
        ),
    ]
