# Generated by Django 2.2.6 on 2020-03-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0012_auto_20200325_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='simlecategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(blank=True, max_length=255, null=True)),
                ('compCategoryCompleted', models.BooleanField()),
                ('compOrder', models.IntegerField()),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('isDuilian', models.BooleanField()),
                ('kobilId', models.IntegerField()),
                ('operationDate', models.DateTimeField(auto_now_add=True)),
                ('playersOrdered', models.BooleanField()),
                ('recordCompleted', models.BooleanField()),
                ('competition', models.IntegerField()),
                ('area', models.IntegerField()),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
