# Generated by Django 2.2.6 on 2020-03-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0013_simlecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tc', models.CharField(blank=True, max_length=120, null=True)),
                ('height', models.CharField(blank=True, max_length=120, null=True)),
                ('weight', models.CharField(blank=True, max_length=120, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=120, null=True, verbose_name='Doğum Yeri')),
                ('motherName', models.CharField(blank=True, max_length=120, null=True, verbose_name='Anne Adı')),
                ('fatherName', models.CharField(blank=True, max_length=120, null=True, verbose_name='Baba Adı')),
                ('profileImage', models.ImageField(blank=True, default='profile/user.png', null=True, upload_to='profile/', verbose_name='Profil Resmi')),
                ('birthDate', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('bloodType', models.CharField(choices=[('AB Rh+', 'AB Rh+'), ('AB Rh-', 'AB Rh-'), ('A Rh+', 'A Rh+'), ('A Rh-', 'A Rh-'), ('B Rh+', 'B Rh+'), ('B Rh-', 'B Rh-'), ('AB Rh+', '0 Rh+'), ('AB Rh+', '0 Rh-')], default='AB Rh+', max_length=128, verbose_name='Kan Grubu')),
                ('gender', models.CharField(choices=[('Erkek', 'Erkek'), ('Kadın', 'Kadın')], default='Erkek', max_length=128, verbose_name='Cinsiyeti')),
                ('postalCode', models.CharField(blank=True, max_length=120, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=120, null=True)),
                ('phoneNumber2', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('shortName', models.CharField(blank=True, max_length=120, null=True)),
                ('foundingDate', models.CharField(blank=True, max_length=120, null=True)),
                ('clubMail', models.CharField(blank=True, max_length=120, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club/', verbose_name='Kulüp Logo')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('isFormal', models.BooleanField()),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. ')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.City', verbose_name='İl')),
                ('clubUser', models.ManyToManyField(to='wushu.SportClubUser')),
                ('coachs', models.ManyToManyField(to='wushu.Coach')),
                ('communication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wushu.Communication')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wushu.Country', verbose_name='Ülke')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
