# Generated by Django 2.2.6 on 2020-03-27 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0014_preregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='clubaddress',
            field=models.TextField(blank=True, null=True, verbose_name='Adres'),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='clubcity',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, to='wushu.City', verbose_name='İl'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preregistration',
            name='clubcountry',
            field=models.ForeignKey(default=45, on_delete=django.db.models.deletion.CASCADE, to='wushu.Country', verbose_name='Ülke'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preregistration',
            name='clubphoneNumber',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='clubphoneNumber2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='clubpostalCode',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
