# Generated by Django 2.2.6 on 2020-03-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0015_auto_20200327_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistration',
            name='communication',
        ),
    ]
