# Generated by Django 2.2.6 on 2020-03-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0017_preregistration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='foundingDate',
            field=models.DateField(blank=True, max_length=120, null=True, verbose_name='Kuruluş Tarihi'),
        ),
    ]
