# Generated by Django 2.2.6 on 2020-03-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0018_auto_20200328_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='dekont',
            field=models.FileField(default='fatih', upload_to='dekont/', verbose_name='Dekont '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preregistration',
            name='petition',
            field=models.FileField(blank=True, null=True, upload_to='dekont/', verbose_name='Dilekçe '),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='isFormal',
            field=models.BooleanField(default=False),
        ),
    ]
