# Generated by Django 2.2.6 on 2020-03-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0019_auto_20200328_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preregistration',
            name='clubUser',
        ),
        migrations.RemoveField(
            model_name='preregistration',
            name='coachs',
        ),
    ]
