# Generated by Django 2.2.6 on 2020-03-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0020_auto_20200328_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='wushu.ClubRole', verbose_name='Üye Rolü'),
            preserve_default=False,
        ),
    ]
