# Generated by Django 2.2.6 on 2020-03-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0021_preregistration_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='reddetwhy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
