# Generated by Django 2.2.6 on 2020-03-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0022_license_reddetwhy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='lisansPhoto',
            field=models.ImageField(upload_to='lisans/', verbose_name='Lisans'),
        ),
    ]
