# Generated by Django 2.2.6 on 2020-03-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0023_auto_20200330_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='lisansPhoto',
            field=models.FileField(upload_to='lisans/', verbose_name='Lisans'),
        ),
    ]
