# Generated by Django 2.2.6 on 2020-04-03 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0024_auto_20200330_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='simlecategory',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='visa',
        ),
    ]
