# Generated by Django 2.2.6 on 2020-04-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0026_auto_20200403_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='visa',
        ),
    ]
