# Generated by Django 2.2.6 on 2020-04-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0027_auto_20200403_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='grades',
            field=models.ManyToManyField(related_name='grades', to='wushu.Level'),
        ),
        migrations.AddField(
            model_name='coach',
            name='visa',
            field=models.ManyToManyField(related_name='visa', to='wushu.Level'),
        ),
    ]
