# Generated by Django 2.2.6 on 2020-04-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0028_auto_20200403_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachlevel',
            name='definition',
        ),
        migrations.DeleteModel(
            name='CoachVisa',
        ),
        migrations.DeleteModel(
            name='CoachLevel',
        ),
    ]
