# Generated by Django 2.2.6 on 2020-04-07 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0029_auto_20200403_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='isFormal',
            field=models.BooleanField(choices=[(True, 'Spor Kulubü'), (False, 'Diger(Özel Salon-Dojo-Sportif Dernek)')], default=True),
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='petition',
            field=models.FileField(default=django.utils.timezone.now, upload_to='dekont/', verbose_name='Dilekçe '),
            preserve_default=False,
        ),
    ]
