# Generated by Django 2.2.6 on 2020-04-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0030_auto_20200407_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaSeminar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1000)),
                ('startDate', models.DateTimeField()),
                ('location', models.CharField(max_length=1000)),
                ('branch', models.CharField(choices=[('AIKIDO', 'AIKIDO'), ('WING CHUN', 'WING CHUN'), ('WUSHU', 'WUSHU'), ('KYOKUSHIN ASHIHARA', 'KYOKUSHIN ASHIHARA'), ('JEET KUNE DO KULELKAVIDO', 'JEET KUNE DO KULELKAVIDO')], max_length=128, verbose_name='Branş')),
                ('status', models.CharField(choices=[('Onaylandı', 'Onaylandı'), ('Onaya Gönderildi', 'Onaya Gönderildi'), ('Reddedildi', 'Reddedildi'), ('Beklemede', 'Beklemede')], default='Beklemede', max_length=128, verbose_name='Kayıt Durumu')),
                ('coach', models.ManyToManyField(to='wushu.Coach')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
