# Generated by Django 2.2.6 on 2020-04-07 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0031_visaseminar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaseminar',
            name='coach',
        ),
        migrations.AddField(
            model_name='visaseminar',
            name='finishDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visaseminar',
            name='subBranch',
            field=models.CharField(choices=[('SANDA', 'SANDA'), ('TAOLU', 'TAOLU')], default=django.utils.timezone.now, max_length=128, verbose_name='Alt Branş'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visaseminar',
            name='type',
            field=models.CharField(choices=[('Uluslararası', 'Uluslararası'), ('Okullar Arası', 'Okullar Arası'), ('Üniversiteler Arası', 'Üniversiteler Arası'), ('Ulusal', 'Ulusal')], default='Ulusal', max_length=128, verbose_name='Türü'),
        ),
        migrations.AlterField(
            model_name='visaseminar',
            name='status',
            field=models.CharField(choices=[('Ön Kayıt Açık', 'Ön Kayıt Açık'), ('Ön Kayıt Tamamlandı', 'Ön Kayıt Tamamlandı'), ('Beklemede', 'Beklemede')], default='Beklemede', max_length=128, verbose_name='Kayıt Durumu'),
        ),
    ]
