# Generated by Django 2.2.6 on 2020-04-09 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0032_auto_20200407_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaseminar',
            name='subBranch',
        ),
        migrations.RemoveField(
            model_name='visaseminar',
            name='type',
        ),
    ]
