# Generated by Django 2.2.6 on 2020-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0033_auto_20200409_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaseminar',
            name='coach',
            field=models.ManyToManyField(to='wushu.Coach'),
        ),
    ]
