# Generated by Django 2.2.6 on 2020-04-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wushu', '0034_visaseminar_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsclub',
            name='isFormal',
            field=models.BooleanField(choices=[(True, 'Spor Kulubü'), (False, 'Diger(Özel Salon-Dojo-Sportif Dernek)')], default=True),
        ),
    ]
