# Generated by Django 2.2.6 on 2020-04-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wushu', '0035_auto_20200411_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaseminar',
            name='status',
            field=models.CharField(choices=[('Onaylandı', 'Onaylandı'), ('Onaya Gönderildi', 'Onaya Gönderildi'),
                                            ('Reddedildi', 'Reddedildi'), ('Beklemede', 'Beklemede')],
                                   default='Beklemede', max_length=128, verbose_name='Kayıt Durumu'),
        ),
    ]
