# Generated by Django 2.2.6 on 2020-04-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wushu', '0036_auto_20200415_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
