# Generated by Django 2.2.6 on 2020-04-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wushu', '0037_license_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='grades',
            field=models.ManyToManyField(related_name='Judgegrades', to='wushu.Level'),
        ),
        migrations.AddField(
            model_name='judge',
            name='visa',
            field=models.ManyToManyField(related_name='Judgevisa', to='wushu.Level'),
        ),
    ]
