# Generated by Django 2.2.6 on 2020-04-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wushu', '0038_auto_20200416_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='isFirst',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
