# Generated by Django 2.2.6 on 2020-04-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wushu', '0039_auto_20200417_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryitem',
            name='isFirst',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
