# Generated by Django 2.2.6 on 2020-04-19 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('wushu', '0041_auto_20200419_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
    ]
