# Generated by Django 2.2.6 on 2020-04-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wushu', '0042_auto_20200419_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='grades',
            field=models.ManyToManyField(related_name='gradesx', to='wushu.Level'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='visa',
            field=models.ManyToManyField(related_name='visax', to='wushu.Level'),
        ),
    ]
