# Generated by Django 2.2.6 on 2020-04-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wushu', '0043_auto_20200419_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='grades',
            field=models.ManyToManyField(related_name='gradesName', to='wushu.Level'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='visa',
            field=models.ManyToManyField(related_name='visaName', to='wushu.Level'),
        ),
    ]
