# Generated by Django 2.2.6 on 2020-04-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wushu', '0044_auto_20200419_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='grades',
            field=models.ManyToManyField(related_name='CoachGrades', to='wushu.Level'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='visa',
            field=models.ManyToManyField(related_name='CoachVisa', to='wushu.Level'),
        ),
    ]
