# Generated by Django 2.2.6 on 2020-04-15 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_deneme_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deneme',
            old_name='id',
            new_name='sifre',
        ),
        migrations.AlterField(
            model_name='deneme',
            name='code',
            field=models.UUIDField(default=uuid.UUID('08f9006c-ce77-4931-a194-bb2c7f93016f'), editable=False),
        ),
    ]
