# Generated by Django 2.2.6 on 2020-04-15 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_auto_20200415_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forgot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sifre', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('modificationDate', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('code', models.UUIDField(default=uuid.UUID('94e60a70-7d01-4cc9-bb96-7b81de8297fa'), editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Deneme',
        ),
    ]
