# Generated by Django 2.2.6 on 2020-04-15 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0007_auto_20200415_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgot',
            name='code',
            field=models.UUIDField(default=uuid.UUID('548d07f9-4378-43bc-9d28-fde1bfbf632e'), editable=False),
        ),
    ]
