# Generated by Django 2.2.6 on 2020-04-15 15:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0008_auto_20200415_1828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Forgot',
        ),
    ]
