# Generated by Django 2.2.6 on 2020-04-15 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0010_forgot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forgot',
            old_name='sifre',
            new_name='uuid',
        ),
        migrations.RemoveField(
            model_name='forgot',
            name='code',
        ),
    ]
