# Generated by Django 2.2.6 on 2020-05-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(blank=True, null=True, upload_to='document/', verbose_name='Document')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('operationDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='epproject',
            name='karakteristik',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Karakteristik'),
        ),
        migrations.AddField(
            model_name='epproject',
            name='projectStatus',
            field=models.CharField(choices=[('Proje devam ediyor', 'Proje devam ediyor'), ('Proje tamamlandı', 'Proje tamamlandı'), ('Deprem Yön. revizyonu yapılıyor', 'Deprem Yön. revizyonu yapılıyor'), ('İhale sürecinde', 'İhale sürecinde')], default='İhale sürecinde', max_length=128, verbose_name='Onay Durumu'),
        ),
        migrations.AddField(
            model_name='epproject',
            name='documents',
            field=models.ManyToManyField(to='sbs.EPDocument'),
        ),
    ]
