# Generated by Django 2.2.6 on 2020-05-14 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epproject',
            name='town',
            field=models.ForeignKey(db_column='town', default=3, on_delete=django.db.models.deletion.CASCADE, to='sbs.Town', verbose_name='İlçe'),
            preserve_default=False,
        ),
    ]
