# Generated by Django 2.2.6 on 2020-05-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0002_auto_20200516_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='epproject',
            name='aifinish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='epproject',
            name='aistart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
