# Generated by Django 2.2.6 on 2020-05-14 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0003_remove_epproject_sorumlu'),
    ]

    operations = [
        migrations.AddField(
            model_name='epproject',
            name='sorumlu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sorumlu', to='sbs.EPEmployee', verbose_name='Sorumlu'),
            preserve_default=False,
        ),
    ]
