# Generated by Django 2.2.4 on 2020-04-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0003_competition_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compathlete',
            name='degree',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='kobilid',
            field=models.IntegerField(db_column='kobilId', default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='kop1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='kop1b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='kop2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='kop2b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='kop3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='kop3b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='kopdegree',
            field=models.IntegerField(db_column='kopDegree', default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='kopkaldirissira',
            field=models.IntegerField(db_column='kopKaldirisSira', default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='kopsilktotal',
            field=models.IntegerField(db_column='kopSilkTotal', default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='koptotal',
            field=models.IntegerField(db_column='kopTotal', default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='lastliftvalue',
            field=models.IntegerField(blank=True, db_column='lastLiftValue', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='lastsilkliftvalue',
            field=models.IntegerField(blank=True, db_column='lastSilkLiftValue', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='lotno',
            field=models.IntegerField(db_column='lotNo', default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='sessionno',
            field=models.IntegerField(db_column='sessionNo', default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='silk1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='silk1b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='silk2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='silk2b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='silk3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='silk3b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='silkdegree',
            field=models.IntegerField(db_column='silkDegree', default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='silktotal',
            field=models.IntegerField(db_column='silkTotal', default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='compathlete',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
