# Generated by Django 2.2.6 on 2020-05-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0004_epproject_sorumlu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epproject',
            name='employees',
            field=models.ManyToManyField(related_name='personel', to='sbs.EPEmployee'),
        ),
    ]
