# Generated by Django 2.2.4 on 2020-04-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0004_auto_20200429_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'default_permissions': (), 'ordering': ['pk']},
        ),
        migrations.AlterModelTable(
            name='athlete',
            table='athlete',
        ),
        migrations.AlterModelTable(
            name='license',
            table='license',
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
        migrations.AlterModelTable(
            name='sportsclub',
            table='sportclub',
        ),
    ]
