# Generated by Django 2.2.4 on 2020-04-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0005_auto_20200430_0140'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoryitem',
            table='categoryitem',
        ),
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
        migrations.AlterModelTable(
            name='communication',
            table='communication',
        ),
        migrations.AlterModelTable(
            name='country',
            table='country',
        ),
    ]
