# Generated by Django 2.2.6 on 2020-05-02 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0008_auto_20200430_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'default_permissions': ()},
        ),
    ]
