# Generated by Django 2.2.6 on 2020-05-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0010_auto_20200502_0518'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoryitem',
            table=None,
        ),
    ]
