# Generated by Django 2.2.6 on 2020-05-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sbs', '0011_auto_20200502_1536'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoryitem',
            table='categoryitem',
        ),
    ]
